# Generated by Django 5.0.7 on 2025-09-01 18:09

import core_apps.candidate.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0003_rename_state_date_votepanelmodel_started_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=core_apps.candidate.models.CandidateImg)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('votepanel', models.ManyToManyField(to='voting.votepanelmodel')),
            ],
        ),
    ]
