# Generated by Django 5.0.7 on 2025-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('voting', '0004_alter_votepanelmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='votepanel',
            field=models.ManyToManyField(related_name='candidate', to='voting.votepanelmodel'),
        ),
    ]
