# Generated by Django 5.2.6 on 2025-09-22 11:48

import core_apps.candidate.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidatemodel_votepanel'),
        ('voting', '0007_alter_votepanelmodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate'},
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Who created candidate'),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Candidate description'),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='image',
            field=models.ImageField(upload_to=core_apps.candidate.models.CandidateImg, verbose_name='Candidate image'),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Candidate name'),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='votepanel',
            field=models.ManyToManyField(related_name='candidate', to='voting.votepanelmodel', verbose_name='Candidate vote panel'),
        ),
        migrations.AlterModelTable(
            name='candidatemodel',
            table='candidate',
        ),
    ]
