# Generated by Django 5.0.7 on 2025-08-27 19:22

import core_apps.voting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotePanelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=core_apps.voting.models.VotePanelImg)),
                ('max_candidate', models.SmallIntegerField()),
                ('max_vote', models.BigIntegerField()),
                ('state_date', models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime')),
                ('is_active', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
