# Generated by Django 5.0.7 on 2025-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepanelmodel',
            name='max_candidate',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='max_vote',
            field=models.BigIntegerField(null=True),
        ),
    ]
