# Generated by Django 5.0.7 on 2025-09-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_votepanelmodel_max_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votepanelmodel',
            old_name='state_date',
            new_name='started_date',
        ),
    ]
