# Generated by Django 5.0.7 on 2025-09-17 19:09

import core_apps.voting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_state_date_votepanelmodel_started_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votepanelmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'VotePanle'},
        ),
        migrations.RemoveField(
            model_name='votepanelmodel',
            name='max_vote',
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Who created vote panel'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='description',
            field=models.CharField(max_length=128, null=True, verbose_name='Description of vote panle'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When voting ended'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=core_apps.voting.models.VotePanelImg, verbose_name='Image of the vote panle'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='is_active',
            field=models.SmallIntegerField(default=0, verbose_name='Vote panle is active or not'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='max_candidate',
            field=models.SmallIntegerField(null=True, verbose_name='Number of candidate can be added'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name of vote panel'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When voting started'),
        ),
        migrations.AlterModelTable(
            name='votepanelmodel',
            table='votepanles',
        ),
    ]
