# Generated by Django 5.2.6 on 2025-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_votepanelmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepanelmodel',
            name='end_date',
            field=models.DateTimeField(verbose_name='When voting ended'),
        ),
    ]
