# Generated by Django 5.2.6 on 2025-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_votepanelmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepanelmodel',
            name='started_date',
            field=models.DateTimeField(verbose_name='When voting started'),
        ),
    ]
