# Generated by Django 5.2.6 on 2025-09-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_votepanelmodel_started_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votepanelmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'VotePanel'},
        ),
    ]
