# Generated by Django 5.2.6 on 2025-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_votepanelmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepanelmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='When voting ended'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='started_date',
            field=models.DateTimeField(blank=True, verbose_name='When voting started'),
        ),
    ]
