# Generated by Django 5.2.6 on 2025-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_votepanelmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votepanelmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When voting ended'),
        ),
        migrations.AlterField(
            model_name='votepanelmodel',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When voting started'),
        ),
    ]
