# Generated by Django 5.2.6 on 2025-10-31 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatemodel_options_and_more'),
        ('votes', '0001_initial'),
        ('voting', '0009_alter_votepanelmodel_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='VotesModel',
        ),
        migrations.AlterModelOptions(
            name='votesmodel',
            options={'ordering': ['-voted_at'], 'verbose_name': 'Votes'},
        ),
        migrations.AlterModelTable(
            name='votesmodel',
            table='votes',
        ),
    ]
