# Generated by Django 5.2.6 on 2025-10-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatemodel_options_and_more'),
        ('votes', '0002_rename_votes_votesmodel_alter_votesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesmodel',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidatemodel'),
        ),
    ]
