# Generated by Django 5.2.6 on 2025-11-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatemodel_options_and_more'),
        ('votes', '0003_alter_votesmodel_candidate'),
        ('voting', '0009_alter_votepanelmodel_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesmodel',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidatemodel', verbose_name='Candidate to assign'),
        ),
        migrations.AlterField(
            model_name='votesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User who votes'),
        ),
        migrations.AlterField(
            model_name='votesmodel',
            name='vote_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.votepanelmodel', verbose_name='Vote panel to assign'),
        ),
        migrations.AlterField(
            model_name='votesmodel',
            name='voted_at',
            field=models.DateTimeField(auto_now=True, verbose_name='When vote added'),
        ),
    ]
