# Generated by Django 5.2.6 on 2025-11-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cancreatepanel',
            field=models.BooleanField(default=0, verbose_name='Allow admin to create panel'),
        ),
        migrations.AddField(
            model_name='users',
            name='maxpanelcount',
            field=models.SmallIntegerField(null=True, verbose_name='Number of panel careation by admins'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=6, null=True, verbose_name='One time password'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_attempt',
            field=models.IntegerField(default=0, verbose_name='One time password attempt'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='One time password expiration'),
        ),
        migrations.CreateModel(
            name='GroupUserAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedtoadmin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admin_relation_to_user', to=settings.AUTH_USER_MODEL, verbose_name='The user who related to')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_relation_to_admin', to=settings.AUTH_USER_MODEL, verbose_name='The user itself')),
            ],
            options={
                'verbose_name': 'User-Groups',
                'db_table': 'usersgroups',
            },
        ),
    ]
