# Generated by Django 5.2.6 on 2025-11-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_cancreatepanel_users_maxpanelcount_users_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='cancreatepanel',
            new_name='allowunlimitpanelcreation',
        ),
    ]
