# Generated by Django 5.2.6 on 2025-11-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_cancreatepanel_users_allowunlimitpanelcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='maxpanelcount',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Number of panel careation by admins'),
        ),
    ]
