# Generated by Django 5.2.6 on 2025-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_maxpanelcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='maxpanelcount',
            field=models.SmallIntegerField(default=0, verbose_name='Number of panel careation by admins'),
        ),
    ]
