# Generated by Django 5.2.6 on 2025-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_users_maxpanelcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='national_code',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Code meli of the user'),
        ),
    ]
