# Generated by Django 5.2.6 on 2025-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='national_code',
            field=models.BigIntegerField(unique=True, verbose_name='Code meli of the user'),
        ),
    ]
