# Generated by Django 5.2.6 on 2025-11-04 18:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+989111111111', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
