# Generated by Django 5.2.6 on 2025-11-04 19:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
