# Generated by Django 5.2.6 on 2025-11-06 10:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='allowunlimitpanelcreation',
            field=models.BooleanField(default=0, verbose_name='Allow admin to create panel ultimately'),
        ),
        migrations.AlterField(
            model_name='users',
            name='national_code',
            field=models.BigIntegerField(unique=True, verbose_name='National code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='Username'),
        ),
    ]
